import type { BlogPost, RepoWithMetaData } from '$lib/types/types';
import type { CssColor } from '$lib/types';

export const COMPONENT_COLORS = ['black', 'red', 'orange', 'yellow', 'green', 'teal', 'blue', 'indigo'] as const;
export const COLOR_FORMATS = ['hex', 'rbg', 'hsl', 'lch', 'oklch', 'lab', 'oklab'] as const;
export const HEX_STRING_FORMATS = ['condensed', 'full'] as const;
export const NUMBER_TYPES = ['hex', 'decimal', 'percent', 'float', 'degree', 'rad', 'turn'] as const;

export const COLOR_SPACE_COMPONENTS = [
	'red',
	'green',
	'blue',
	'alpha',
	'hue',
	'sat',
	'light',
	'chroma',
	'aaxis',
	'baxis',
] as const;

export const BASIC_ICON_NAMES = [
	'angledoubleleft',
	'angledoubleright',
	'arrow',
	'arrowdown',
	'arrowleft',
	'arrowright',
	'arrowup',
	'asterisk',
	'beziercurve',
	'cancel',
	'caretdown',
	'caretup',
	'check',
	'checked',
	'chevron',
	'chevronleft',
	'chevronright',
	'chevronup',
	'circlefull',
	'circleoutline',
	'close',
	'code',
	'colorswatches',
	'copy',
	'database',
	'deselect',
	'doubleup',
	'edit',
	'editfilled',
	'email',
	'exclamation',
	'exclamationtriangle',
	'export',
	'fastbackward',
	'fastforward',
	'filter',
	'folderopen',
	'fork',
	'gear',
	'globe',
	'halfstar',
	'handlizard',
	'handpointup',
	'handshake',
	'hashtag',
	'help',
	'keyboard',
	'link',
	'menu',
	'minus',
	'minussquare',
	'ok',
	'open',
	'palette',
	'palettewithbrush',
	'pause',
	'pencil',
	'play',
	'plus',
	'plussquare',
	'projectdiagram',
	'removefilters',
	'reset',
	'returnright',
	'save',
	'selectall',
	'selectnone',
	'shellprompt',
	'sort',
	'star',
	'staroutline',
	'stepbackward',
	'stepforward',
	'trash',
	'unchecked',
] as const;

export const SOCIAL_ICON_NAMES = [
	'codepen',
	'github',
	'githubsquare',
	'linkedin',
	'linkedinsquare',
	'twitter',
	'twittersquare',
] as const;

export const LANGTECH_ICON_NAMES = [
	'aws',
	'cypress',
	'fastapi',
	'flask',
	'hugo',
	'microsoft',
	'playwright',
	'puppeteer',
	'python',
	'redis',
	'regexp',
	'sqlite',
	'svelte',
	'tailwind',
	'typescript',
	'xml',
	'xstate',
] as const;

export const X11_NAMED_COLORS = [
	'AliceBlue',
	'AntiqueWhite',
	'Aqua',
	'Aquamarine',
	'Azure',
	'Beige',
	'Bisque',
	'Black',
	'BlanchedAlmond',
	'Blue',
	'BlueViolet',
	'Brown',
	'BurlyWood',
	'CadetBlue',
	'Chartreuse',
	'Chocolate',
	'Coral',
	'CornflowerBlue',
	'Cornsilk',
	'currentcolor',
	'Crimson',
	'Cyan',
	'DarkBlue',
	'DarkCyan',
	'DarkGoldenRod',
	'DarkGray',
	'DarkGrey',
	'DarkGreen',
	'DarkKhaki',
	'DarkMagenta',
	'DarkOliveGreen',
	'Darkorange',
	'DarkOrchid',
	'DarkRed',
	'DarkSalmon',
	'DarkSeaGreen',
	'DarkSlateBlue',
	'DarkSlateGray',
	'DarkSlateGrey',
	'DarkTurquoise',
	'DarkViolet',
	'DeepPink',
	'DeepSkyBlue',
	'DimGray',
	'DimGrey',
	'DodgerBlue',
	'FireBrick',
	'FloralWhite',
	'ForestGreen',
	'Fuchsia',
	'Gainsboro',
	'GhostWhite',
	'Gold',
	'GoldenRod',
	'Gray',
	'Grey',
	'Green',
	'GreenYellow',
	'HoneyDew',
	'HotPink',
	'IndianRed',
	'Indigo',
	'inherit',
	'Ivory',
	'Khaki',
	'Lavender',
	'LavenderBlush',
	'LawnGreen',
	'LemonChiffon',
	'LightBlue',
	'LightCoral',
	'LightCyan',
	'LightGoldenRodYellow',
	'LightGray',
	'LightGrey',
	'LightGreen',
	'LightPink',
	'LightSalmon',
	'LightSeaGreen',
	'LightSkyBlue',
	'LightSlateGray',
	'LightSlateGrey',
	'LightSteelBlue',
	'LightYellow',
	'Lime',
	'LimeGreen',
	'Linen',
	'Magenta',
	'Maroon',
	'MediumAquaMarine',
	'MediumBlue',
	'MediumOrchid',
	'MediumPurple',
	'MediumSeaGreen',
	'MediumSlateBlue',
	'MediumSpringGreen',
	'MediumTurquoise',
	'MediumVioletRed',
	'MidnightBlue',
	'MintCream',
	'MistyRose',
	'Moccasin',
	'NavajoWhite',
	'Navy',
	'OldLace',
	'Olive',
	'OliveDrab',
	'Orange',
	'OrangeRed',
	'Orchid',
	'PaleGoldenRod',
	'PaleGreen',
	'PaleTurquoise',
	'PaleVioletRed',
	'PapayaWhip',
	'PeachPuff',
	'Peru',
	'Pink',
	'Plum',
	'PowderBlue',
	'Purple',
	'Red',
	'RosyBrown',
	'RoyalBlue',
	'SaddleBrown',
	'Salmon',
	'SandyBrown',
	'SeaGreen',
	'SeaShell',
	'Sienna',
	'Silver',
	'SkyBlue',
	'SlateBlue',
	'SlateGray',
	'SlateGrey',
	'Snow',
	'SpringGreen',
	'SteelBlue',
	'Tan',
	'Teal',
	'Thistle',
	'Tomato',
	'transparent',
	'Turquoise',
	'Violet',
	'Wheat',
	'White',
	'WhiteSmoke',
	'Yellow',
	'YellowGreen',
];

export const defaultCssColor: CssColor = {
	hex: '',
	rgb: { r: 0, g: 0, b: 0, a: 255 },
	hsl: { h: 0, s: 0, l: 0, a: 255 },
	lab: { l: 0, a: 0, b: 0, A: 255 },
	oklab: { l: 0, a: 0, b: 0, A: 255 },
	lch: { l: 0, c: 0, h: 0, a: 255 },
	oklch: { l: 0, c: 0, h: 0, a: 255 },
	okhsl: { h: 0, s: 0, l: 0, a: 255 },
	rgbString: '',
	hslString: '',
	labString: '',
	oklabString: '',
	lchString: '',
	oklchString: '',
	okhslString: '',
	hasAlpha: false,
	name: '',
};


export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS', 'CONNECT'] as const;

export const HTTP_AUTH_TYPES = ['Basic', 'Token'] as const;

export const ICON_NAMES = ['fork', 'github', 'star'] as const;

export const ICON_COLORS = [
	'red',
	'yellow',
	'yellow-green',
	'green',
	'blue',
	'dark-blue',
	'purple',
	'pink',
	'teal',
	'orange',
	'default',
] as const;

export const NAV_ICON_NAMES = [
	'androidmask',
	'audiocassette',
	'boltspellcast',
	'cybereye',
	'dustcloud',
	'firesilhouette',
	'heptagram',
	'highfive',
	'moebiusstar',
	'orbital',
	'ramprofile',
	'spatter',
	'stairs3d',
	'summits',
	'sverdifjell',
	'teleport',
] as const;

export const TECH_LIST = [
	'allLanguages',
	'AWS',
	'CSharp',
	'Cypress',
	'FastAPI',
	'Flask',
	'Hugo',
	'lxml',
	'Puppeteer',
	'Playwright',
	'Pydantic',
	'Python',
	'Redis',
	'RegExp',
	'Shell',
	'SQLAlchemy',
	'SQLite',
	'Svelte',
	'TailwindCSS',
	'TypeScript',
	'XPath',
	'XState',
] as const;

export const REPO_NAMES = [
	'null',
	'aaronluna.dev',
	'async-file-server',
	'console-progress-bar',
	'dotnetcore-crypto',
	'fastapi-redis-cache',
	'flask-api-tutorial',
	'packer-examples',
	'svelte-base64-ts',
	'svelte-base64',
	'svelte-color-tools',
	'svelte-simple-tables-docs',
	'svelte-simple-tables',
	'unicode-api',
	'vig-api',
	'vig-data',
	'vigorish',
] as const;

export const FEATURED_PROJECTS = [
	'fastapi-redis-cache',
	'svelte-base64-ts',
	'svelte-color-tools',
	'svelte-simple-tables',
	'unicode-api',
	'vigorish',
];

export const PROJECT_TYPES = ['allProjects', 'backend', 'frontend'] as const;

export const FRONTEND_CATEGORIES = ['blog_portfolio_sites', 'docs_guides', 'web_app', 'component_library'] as const;

export const BACKEND_CATEGORIES = [
	'rest_api',
	'cli_apps',
	'cryptography',
	'dev_tools',
	'devops',
	'fastapi_plugins',
	'virtualization',
	'web_scraping',
] as const;

export const PROJECT_CATEGORIES = ['allCategories', ...BACKEND_CATEGORIES, ...FRONTEND_CATEGORIES] as const;

export const nullRepoWithMetadata: RepoWithMetaData = {
	name: 'null',
	description: '',
	starCount: 0,
	forkCount: 0,
	repoUrl: '',
	starsUrl: '',
	forksUrl: '',
	primaryLanguage: 'allLanguages',
	primaryCategory: 'allProjects',
	languages: ['allLanguages'],
	categories: ['allCategories'],
	updatedAt: '',
};

export const nullBlogPost: BlogPost = {
	content: '',
	title: '',
	subtitle: '',
	description: '',
	frontmatter: {},
	hasToc: false,
	category: 'allCategories',
	language: 'allLanguages',
	categories: [],
	techList: [],
	canonical: '',
	slug: '',
	url: '',
	date: '',
	coverImage: {
		name: '',
		src: '',
		caption: '',
	},
	resources: {},
};
