[build]
  command = "pnpm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "16" 
  ## as of v0.334 sveltekit requires node 16 https://github.com/sveltejs/kit/pull/4922
  ## https://github.com/sveltejs/kit/issues/2687

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["mdsvex"]
  
[[plugins]]
  package = "/netlify-plugin-pnpm"

[[headers]]
  ## https://answers.netlify.com/t/content-type-header-not-working-in-netlify-toml/7718
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=4000" 
    # cache just over 1 hour for webpagetest to be happy
    X-Content-Type-Options = "nosniff"
    ## Content-Security-Policy = "default-src 'self'; script-src 'nonce-swyx'; img-src *"
