[build]
exclude = [
  "README.md"
  #, and/or another other files that are not relevant
  # to the build
]

[[build.env]]
name = "BP_NODE_RUN_SCRIPTS"
value = "build"

[[build.env]]
name = "NODE_ENV"
value = "dev"